version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "samiwarraich"
    reviewers:
      - "samiwarraich"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
